In [4]:
import numpy as np
A=np.random.rand(3,2)
A

array([[0.3291831 , 0.83303743],
       [0.96195715, 0.56920053],
       [0.97775102, 0.46127559]])

In [5]:
B=np.random.rand(3,2)
B

array([[0.81026026, 0.02913159],
       [0.10167416, 0.1971891 ],
       [0.40627542, 0.67598596]])

In [6]:
A*B

array([[0.26672399, 0.0242677 ],
       [0.09780618, 0.11224014],
       [0.39723621, 0.31181582]])

In [9]:
5*B

array([[4.0513013 , 0.14565793],
       [0.50837079, 0.98594552],
       [2.03137711, 3.37992981]])

In [8]:
A@B.T

array([[0.29099169, 0.19773532, 0.69686061],
       [0.79601737, 0.21004633, 0.77559112],
       [0.80567048, 0.19037053, 0.70905203]])

# Q1



In the notes, you have seen that ridge regression corresponds to solving
$$
\hat{\beta}_{\text{ridge}}
=
\arg\min_{\beta\in\mathbb{R}^p}
\left\{
\|y-X\beta\|^2+\lambda\|\beta\|^2
\right\}.
$$
We now consider a probabilistic view of linear regression and show that it leads to the same solution. Define the dataset as $X = \{ x_{1:n}\}$ and $y = \{y_{1:n}\}$, and assume the following model:
$$
y_i = x_i^T\beta + \varepsilon_i,
\qquad
\varepsilon_i \overset{\text{i.i.d.}}{\sim}\mathcal N(0,\sigma^2),
$$
or equivalently,
$$
y_i\mid x_i,\beta \sim \mathcal N(x_i^T\beta,\sigma^2).
$$
Assume also the prior
$$
\beta \sim \mathcal N(0,\sigma_p^2 I_p).
$$
We define the MAP estimator by
$$
\hat\beta_{\text{MAP}}
=
\arg\max_\beta p(\beta\mid X,y).
$$

**Question:** Show that $\hat\beta_{\text{MAP}}$ is equal to the ridge regression solution for a suitable choice of $\lambda$.

You may use the following facts:

- Bayes’ rule:
  $$
  p(\beta\mid X,y)\propto p(y\mid X,\beta)p(\beta)
  $$

- Conditional independence:
  $$
  p(y\mid X,\beta)=\prod_{i=1}^n p(y_i\mid x_i,\beta)
  $$

- Applying $\log$ preserves the maximizer

- Terms that do not depend on $\beta$ may be ignored when optimizing over $\beta$

Derive the corresponding optimization problem explicitly, and state the relationship between $\lambda$, $\sigma^2$, and $\sigma_p^2$.

**Remark**: Your score will be based only on your response in the field " $\lambda:=\ldots$ ". However, to receive credit, you must still upload your derivation.

==**Ans:** $\lambda := \sigma^2/\sigma^2_p$.==

==Solution from the book:==

- <img src="assets/image-20260410153635541.png" alt="image-20260410153635541" style="zoom:50%;" />

$$
\begin{align}
\hat \beta &= \arg \max -\frac12 \left[ \sigma_p^{-2} ||\beta||^2_2 + \sigma^{-2} ||y - X\beta||^2_2 \right] \\
%
&= \arg \min \left[ \sigma_p^{-2} ||\beta||^2_2 + \sigma^{-2} ||y - X\beta||^2_2 \right] \\
%
&= \arg \min \sigma^2 \left[ \sigma_p^{-2} ||\beta||^2_2 + \sigma^{-2} ||y - X\beta||^2_2 \right] \\
%
&= \arg \min  \left[ \frac{\sigma^2}{\sigma_p^{2}} ||\beta||^2_2 + ||y - X\beta||^2_2 \right] \\
\end{align}
$$





# Q2

<img src="assets/calc bias larger.drawio_05_chromatic_shift-1776674560673-2.png" alt="calc bias larger.drawio_05_chromatic_shift" style="zoom:50%;" />

Based on the figure, consider the true regression function marked as $f^*$ (in blue). Suppose we fit two regression models to different independent and identically distributed (i.i.d.) datasets sampled from the true regression function, $\mathcal{D}_1, \mathcal{D}_2$, resulting in the two red-tinted models in the figure.



For which point $x_0 \in \mathbb{N}$ do you expect the squared bias of the average predictor relative to $f^*(x_0)$ to be the largest?

1. $x_0 = ...$



At this point $x_0$, compute:

1. The sample mean of the predictions $f_{i}\left(x_0\right)$.
2. The squared bias relative to $f^*\left(x_0\right)$.
3. The variance of the predictors at $x_0$ (note that we use in this lecture the biased sample variance, as it is computed by numpy).



==Answers:== 

1. x_0=21

2. 

   1. f1 = 11, f2=9, f*=7. -> sample mean 10
   2. $bias^2$ = $(7-10)^2=9$
   3. variance = $\frac{1}{2}((10 - 11)^2 + ((10-9)^2))=1$

   



# Q3 - Cross-Validation Folds

Run `student_starter.py`. It loads two datasets, "regression_iid" and "forecasting", and visualizes three fold procedures: `A`, `B`, and `C`.

The `forecasting` dataset is time-ordered: the model uses $x=y_t$ to predict $y=y_{t+1}$. The goal is thus to predict the next value from the current value.

**Question 1:** Match each procedure to the correct description.

Descriptions:
1. Random split
2. Systematic interleaved split
3. Train on earlier samples and test on later ones.

Answers:

1. Procedure A is description: `1`, `2`, or `3`.
2. Procedure B is description: `1`, `2`, or `3`.
3. Procedure C is description: `1`, `2`, or `3`.



**Question 2**

For regression_iid, the rows may be treated as independent samples with no meaningful time order.

Which fold procedure(s) would you use to obtain a reliable MSE estimate? Select all that apply: `A`, `B`, `C`.



**Question 3**

Which fold procedure(s) would you use to obtain a reliable MSE estimate? Select all that apply: `A`, `B`, `C`.



==Answers==

1. A -> 1, B -> 2, C -> 3
2. A, B
3. C

